name: mac

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build ROOT
      run: |
        curl -O https://root.cern/download/root_v6.20.02.source.tar.gz
        tar xf root_v6.20.02.source.tar.gz
        mkdir build
        mkdir root
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=../root -Dcxx17=ON ../root-6.20.02
        ninja
        ninja install
        cd ..
        tar zcf root.tgz root/
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: root.tgz